#date 27-02-2026
#fastAPI app Dockerfile by python


#  FROM python:3.10
#  WORKDIR /app
#  COPY requirements.txt
#  RUN pip install -r requirements.txt
#  COPY ..
#  EXPOSE 8000
#  CMD["python","appy.py"]

#simple pyhton script runner Dockerfile

# FROM python:3.10
# WORKDIR /app
# COPY ..
# RUN pip install requirement.txt
# CMD ["python","script.py"]


#springbooot dockerfile

# FROM openjdk:17
# WORKDIR /app
# COPY tsrget /app.jar app.jar
# EXPOSE 8080 
# CMD ["java","-jar","app.jar"]

#java maven build dockerfile
# FROM maven:3.9-openjdk -17
# WORKDIR /app
# COPY ..
# EXPOSE 8080
# CMD ["java" , "-jar", "target/*.jar"]
#simple java app dockerfile
# FROM openjdk:17
# WORKDIR /app
# COPY ..
# RUN javac main java
# CMD ["java","main"]


#node js app dockerfile
# FROM node:18
# WORKDIR /app
# COPY  package*.json
# RUN nmp install
# COPY ..
# EXPOSE 3000
# CMD ["node","app.js"]




#   29-05-2026

# FROM python:3-10-slim
# WORKDIR /app
# COPY requirement.txt 
# RUN pip install requirememt.txt
# COPY ..
# EXPOSE 5000
# CMD ["python", "appy.py"]



# FROM python:3-10
# WORKDIR /app
# COPY requirement.txt
# RUN pip install -r 
# COPY ..
# EXPOSE 8000
# CMD ["python", "appy.py"]


# FROM python:3.10
# WORKDIR /app
# COPY  requirement.txt
# RUN pip install -r requirement.txt
# CMD ["python", "script.py"]



# FROM  openjdk:17
# WORKDIR /app
# COPY target /app.jar app.jar
# EXPOSE 8080
# CMD ["java", "app.java"]
