name: multi step pipeline

on:
  push:
    branches:
      - main

jobs:           # This is the job ID
    runs-on: ubuntu-latest # Shifted 2 spaces right
    steps:               # Shifted 2 spaces right
      - name: step 1
        run: echo "This is step 1"

      - name: step 2
        run: echo "This is step 2"

      - name: step 3
        run: echo "This is step 3"
