name: sarang checking

  on:
    push:
     branches:
      - main

  jobe:
      sarang:
        runs-on: ubuntu-latest
          steps:

           - name: sarang checking
            eacho: sarang
